using System.Collections.Generic;
using System.IO;

namespace FIFA15.AccessoryManager
{
    public class LuaAssignmentGenerator
    {
        public static void GenerateShoesLua(IEnumerable<Player> players, string outputPath)
        {
            using (var writer = new StreamWriter(outputPath, false))
            {
                writer.WriteLine("-- Generated by FIFA 15 Accessory Manager");
                foreach (var player in players)
                {
                    if (player.ShoeId > 0)
                    {
                        writer.WriteLine($"assignShoe({player.PlayerId}, {player.ShoeId})");
                    }
                }
            }
        }

        public static void GenerateGkGlovesLua(IEnumerable<Player> players, string outputPath)
        {
            var lines = new List<string>();
            lines.Add("-- Generated GK Gloves Assignments");
            foreach (var p in players)
            {
                if (p.GkGloveId > 0)
                {
                    lines.Add($"assignGkGlove({p.PlayerId}, {p.GkGloveId})");
                }
            }
            File.WriteAllLines(outputPath, lines);
        }

        public static void GenerateAnkleTapesLua(IEnumerable<Player> players, string outputPath)
        {
            var lines = new List<string>();
            lines.Add("-- Generated Ankle Tape / Gripsocks Assignments");
            foreach (var p in players)
            {
                // AnkleTapeId stores the color index, which can be 0. Unassigned is -1.
                if (p.AnkleTapeId >= 0)
                {
                    lines.Add($"assignAnkletape({p.PlayerId}, {p.AnkleTapeId})");
                }
            }
            File.WriteAllLines(outputPath, lines);
        }
    }
}
