<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="FifaLibrary14">
      <HintPath>..\src\FIFA15.ScoreboardManager\bin\Debug\net48\FifaLibrary14.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
